### ISSUE TITLE
Fail to install gen using Go 1.4 go get command

### ISSUE THREAD

**Issue by marciodasilva** [clipperhouse/stringer#2]
go get github.com/clipperhouse/gen generates clipperhouse/typewriter/package.go:48: assignment count mismatch: 2 = 3

**Comment by clipperhouse** [comment]
I think you might have an older version of the types package. Try:

`go get -u golang.org/x/tools/go/types`

and then

`go get github.com/clipperhouse/gen`

once more

**Comment by marciodasilva** [comment]
Thanks Matt,
It worked after I downloaded and rebuilt the entire tools package (some were renamed). I look forward to use the "gen" package on my project. Do you have a tutorial that I can use to get started?
Many thanks in advance,
Marcio

**Comment by clipperhouse** [comment]
Thanks Marcio, there are some [docs here](http://clipperhouse.github.io/gen/) and a [video here](https://www.youtube.com/watch?v=KY8OXFi3CDU) which might be helpful.
